#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/070-mechanik/1-lagrange.tex				\
	chapters/070-mechanik/2-hamilton.tex				\
	chapters/070-mechanik/3-jacobi.tex				\
	chapters/070-mechanik/chapter.tex
