#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-planet =						\
	papers/planet/packages.tex					\
	papers/planet/main.tex					\
	papers/planet/references.bib				\
	papers/planet/teil0.tex					\
	papers/planet/teil1.tex					\
	papers/planet/teil2.tex					\
	papers/planet/teil3.tex

