#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-planet =						\
	papers/planet/packages.tex				\
	papers/planet/main.tex					\
	papers/planet/references.bib				\
	papers/planet/0_Einleitung.tex				\
	papers/planet/1_Berechnungen.tex			\
	papers/planet/2_Multipol.tex				\
	papers/planet/3_Arrokoth.tex				\
	papers/planet/4_Goce.tex

