#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-doppelpendel =						\
	papers/doppelpendel/packages.tex				\
	papers/doppelpendel/main.tex					\
	papers/doppelpendel/references.bib				\
	papers/doppelpendel/teil0.tex					\
	papers/doppelpendel/teil1.tex					\
	papers/doppelpendel/teil2.tex					\
	papers/doppelpendel/teil3.tex

