#
# Makefile -- build drawings
#
# (c) 2024 Prof Dr Andreas Müller
#
all:	balken.pdf biegelinie.pdf

balken.pdf:	balken.tex
	pdflatex balken.tex

biegelinie.pdf:	biegelinie.tex
	pdflatex biegelinie.tex


