#
# Makefile.inc -- Makefile dependencies for chapter 5
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/050-nebenbedingungen/1-lagrangemult.tex		\
	chapters/050-nebenbedingungen/2-transversal.tex			\
	chapters/050-nebenbedingungen/fig/dido.tex			\
	chapters/050-nebenbedingungen/chapter.tex
