#
# Makefile.inc -- Makefile dependencies for chapter 5
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/050-variation2/1-hinreichend.tex			\
	chapters/050-variation2/2-zweiteableitung.tex			\
	chapters/050-variation2/chapter.tex
