#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-widerstand =						\
	papers/widerstand/packages.tex					\
	papers/widerstand/main.tex					\
	papers/widerstand/references.bib				\
	papers/widerstand/widerstand.tex				\
	papers/widerstand/loesung.tex	

