#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-balken =						\
	papers/balken/packages.tex					\
	papers/balken/main.tex					\
	papers/balken/references.bib				\
	papers/balken/teil0.tex					\
	papers/balken/teil1.tex					\
	papers/balken/teil2.tex					\
	papers/balken/teil3.tex

