#
# Makefile -- build images
#
# (c) 2023 Prof Dr Andreas Müller
#
all:	ritzloesung.pdf abstieg.pdf

ritzloesung.pdf:	ritzloesung.tex
	pdflatex ritzloesung.tex

abstieg.pdf:	abstieg.tex
	pdflatex abstieg.tex

