#
# Makefile.inc -- Makefile dependencies for chapter 3
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/030-felder/1-fundamentallemma.tex			\
	chapters/030-felder/2-ostrogradski.tex				\
	chapters/030-felder/3-vektorfelder.tex				\
	chapters/030-felder/chapter.tex
