#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/070-direkt/1-gradient.tex				\
	chapters/070-direkt/2-ritz.tex					\
	chapters/070-direkt/3-fem.tex					\
	chapters/070-direkt/fig/ritzloesung.tex				\
	chapters/070-direkt/fig/abstieg.tex				\
	chapters/070-direkt/chapter.tex
