#
# Makefile.inc -- Makefile dependencies for chapter 7
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/070-direkt/gradient.tex				\
	chapters/070-direkt/ritz.tex					\
	chapters/070-direkt/fem.tex					\
	chapters/070-direkt/chapter.tex
