#
# Makefile.inc
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter3 =								\
	../slides/3/dido.tex						\
	../slides/3/gradient.tex					\
	../slides/3/lagrangemultiplikatoren.tex				\
	../slides/3/nebenbedingungen.tex
