#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-minimalflaechen =						\
	papers/minimalflaechen/packages.tex					\
	papers/minimalflaechen/main.tex					\
	papers/minimalflaechen/references.bib				\
	papers/minimalflaechen/teil0.tex					\
	papers/minimalflaechen/teil1.tex					\
	papers/minimalflaechen/teil2.tex					\
	papers/minimalflaechen/teil3.tex

