#
# Makefile.inc
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter6 =								\
	../slides/6/problemtypen.tex					\
	../slides/6/freierrand.tex					\
	../slides/6/variation.tex					\
	../slides/6/hermite.tex						\
	../slides/6/refraktion.tex					\
	../slides/6/spline.tex
