/*
 * common.inc -- gemeinsame Definition für Koordinatenabbildung
 *
 * (c) 2024 Prof Dr Andreas Müller
 */
/*
#declare rot   = rgb<1.0,0.6,0.8>;
#declare gruen = rgb<0.8,1.0,0.6>;
#declare blau  = rgb<0.6,0.8,1.0>;
*/

#declare rot   = rgb<0.8,0.4,0.6>;
#declare gruen = rgb<0.6,0.8,0.4>;
#declare blau  = rgb<0.4,0.6,0.8>;

#declare O = <0, 0, 0>;

#declare R = 2;

#declare h = 0.5;

#declare Xmin = -1.0;
#declare Xmax = 1.0;
#declare Xstep = h;

#declare Ymin = -1.0;
#declare Ymax = 1.0;
#declare Ystep = h;

#declare Zmin = 0;
#declare Zmax = 2;
#declare Zstep = h;

