#
# Makefile -- build images
#
# (c) 2023 Prof Dr Andreas Müller
#
all:	2drand.pdf							\
	greenbeweis.pdf							\
	offen.pdf

2drand.pdf:	2drand.tex
	pdflatex 2drand.tex

greenbeweis.pdf:	greenbeweis.tex
	pdflatex greenbeweis.tex

offen.pdf:	offen.tex
	pdflatex offen.tex

