#
# Makefile
#
# (c) 2024 Prof Dr Andreas Müller
#
all:	a2.pdf a3.pdf a4.pdf a5.pdf

a2.pdf:	a2.tex
	pdflatex a2.tex

a3.pdf:	a3.tex
	pdflatex a3.tex

a4.pdf:	a4.tex
	pdflatex a4.tex

a5.pdf:	a5.tex
	pdflatex a5.tex

