#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-geodaeten =						\
	papers/geodaeten/packages.tex					\
	papers/geodaeten/main.tex					\
	papers/geodaeten/references.bib				\
	papers/geodaeten/teil2.tex					\
	papers/geodaeten/teil3.tex

