#
# Makefile.inc -- Makefile dependencies for chapter 4
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/040-nebenbedingungen/1-lagrangemult.tex		\
	chapters/040-nebenbedingungen/2-transversal.tex			\
	chapters/040-nebenbedingungen/chapter.tex
