#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-cahnhilliard =						\
	papers/cahnhilliard/packages.tex					\
	papers/cahnhilliard/main.tex					\
	papers/cahnhilliard/references.bib				\
	papers/cahnhilliard/teil0.tex					\
	papers/cahnhilliard/teil1.tex					\
	papers/cahnhilliard/teil2.tex					\
	papers/cahnhilliard/teil3.tex

