#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-cahnhilliard =						\
	papers/cahnhilliard/packages.tex					\
	papers/cahnhilliard/main.tex					\
	papers/cahnhilliard/references.bib				\
	papers/cahnhilliard/energie.tex     \
	papers/cahnhilliard/herleitung.tex     \
	papers/cahnhilliard/spinodal.tex

