#
# Makefile.inc -- Makefile dependencies for chapter 10
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/100-symmetrien/1-symmetrie.tex				\
	chapters/100-symmetrien/2-noether.tex				\
	chapters/100-symmetrien/fig/phi.tex				\
	chapters/100-symmetrien/uebungsaufgaben/1001.tex		\
	chapters/100-symmetrien/chapter.tex
