#
# Makefile.inc -- Makefile dependencies for chapter 9
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/090-mechanik/1-lagrange.tex				\
	chapters/090-mechanik/2-hamilton.tex				\
	chapters/090-mechanik/3-jacobi.tex				\
	chapters/090-mechanik/fig/kapiza.tex				\
	chapters/090-mechanik/chapter.tex
