#
# Makefile -- build images
#
# (c) 2023 Prof Dr Andreas Müller
#
all:	brachistochronenproblem.pdf					\
	f.pdf								\
	g.pdf

brachistochronenproblem.pdf:	brachistochronenproblem.tex
	pdflatex brachistochronenproblem.tex

f.pdf:	f.tex
	pdflatex f.tex

g.pdf:	g.tex
	pdflatex g.tex

