#
# Makefile -- build images
#
# (c) 2023 Prof Dr Andreas Müller
#
all:	bernoulli.pdf							\
	brachistochronenproblem.pdf					\
	f.pdf								\
	g.pdf								\
	singulaer.pdf							\
	variation0.pdf							\
	variation1.pdf							\
	variation.pdf

bernoulli.pdf:	bernoulli.tex
	pdflatex bernoulli.tex

brachistochronenproblem.pdf:	brachistochronenproblem.tex
	pdflatex brachistochronenproblem.tex

f.pdf:	f.tex
	pdflatex f.tex

g.pdf:	g.tex
	pdflatex g.tex

variation0.pdf:	variation0.tex
	pdflatex variation0.tex

variation1.pdf:	variation1.tex
	pdflatex variation1.tex

variation.pdf:	variation.tex
	pdflatex variation.tex

singulaer.pdf:	singulaer.tex
	pdflatex singulaer.tex

