#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-schwimmen =						\
	papers/schwimmen/packages.tex					\
	papers/schwimmen/main.tex					\
	papers/schwimmen/references.bib				\
	papers/schwimmen/teil0.tex					\
	papers/schwimmen/teil1.tex					\
	papers/schwimmen/teil2.tex					\
	papers/schwimmen/teil3.tex

