#
# Makefile
#
# (c) 2024 Prof Dr Andreas Müller
#
all:	dbr.pdf brechung.pdf nichtdiff.pdf

dbr.pdf:	dbr.tex
	pdflatex dbr.tex

brechung.pdf:	brechung.tex
	pdflatex brechung.tex

nichtdiff.pdf:	nichtdiff.tex
	pdflatex nichtdiff.tex

