#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-maxwell =						\
	papers/maxwell/packages.tex					\
	papers/maxwell/main.tex					\
	papers/maxwell/references.bib				\
	papers/maxwell/teil0.tex					\
	papers/maxwell/teil1.tex					\
	papers/maxwell/teil2.tex					\
	papers/maxwell/teil3.tex

