#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-luke =						\
	papers/luke/packages.tex					\
	papers/luke/main.tex					\
	papers/luke/references.bib

