#
# Makefile.inc -- Makefile dependencies for chapter 8
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/080-symmetrien/1-symmetrie.tex				\
	chapters/080-symmetrien/2-noether.tex				\
	chapters/080-symmetrien/chapter.tex
