#
# Makefile.inc
#
# (c) 2023 Prof Dr Andreas Müller, OST Hochschule
#
include ../slides/0/Makefile.inc
include ../slides/1/Makefile.inc
include ../slides/2/Makefile.inc
include ../slides/3/Makefile.inc

slides =								\
	$(chapter0) $(chapter1) $(chapter2) $(chapter3)
