#
# Makefile.inc -- Makefile dependencies for chapter 6
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/060-variation2/1-zweitevariation.tex			\
	chapters/060-variation2/2-legendree.tex				\
	chapters/060-variation2/3-diffgl.tex				\
	chapters/060-variation2/4-jacobi.tex				\
	chapters/060-variation2/chapter.tex
