#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-circuit =						\
	papers/circuit/packages.tex					\
	papers/circuit/main.tex					\
	papers/circuit/references.bib				\
	papers/circuit/teil0.tex					\
	papers/circuit/teil1.tex					\
	papers/circuit/teil2.tex					\
	papers/circuit/teil3.tex

