#
# Makefile.inc -- Makefile dependencies for chapter 3
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/040-felder/1-fundamentallemma.tex			\
	chapters/040-felder/2-ostrogradski.tex				\
	chapters/040-felder/3-vektorfelder.tex				\
	chapters/040-felder/fig/garbageman.tex				\
	chapters/040-felder/fig/mandelbrot.tex				\
	chapters/040-felder/chapter.tex
