#
# Makefile.inc -- Makefile dependencies for chapter 3
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/040-felder/1-fundamentallemma.tex			\
	chapters/040-felder/11-gebiet.tex				\
	chapters/040-felder/12-partint.tex				\
	chapters/040-felder/13-glatt.tex				\
	chapters/040-felder/14-fundamtentallemma.tex			\
	chapters/040-felder/2-ostrogradski.tex				\
	chapters/040-felder/3-vektorfelder.tex				\
	chapters/040-felder/fig/offen.tex				\
	chapters/040-felder/fig/2drand.tex				\
	chapters/040-felder/fig/randdef.tex				\
	chapters/040-felder/fig/unterteilung.tex			\
	chapters/040-felder/fig/green-beweis.tex			\
	chapters/040-felder/fig/garbageman.tex				\
	chapters/040-felder/fig/mandelbrot.tex				\
	chapters/040-felder/fig/gauss.tex				\
	chapters/040-felder/chapter.tex
