#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-beispiel =						\
	papers/beispiel/packages.tex					\
	papers/beispiel/main.tex					\
	papers/beispiel/references.bib				\
	papers/beispiel/teil0.tex					\
	papers/beispiel/teil1.tex					\
	papers/beispiel/teil2.tex					\
	papers/beispiel/teil3.tex

