#
# Makefile.inc -- Makefile dependencies for chapter 3
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/030-nichtdiff/1-duboisreymond.tex			\
	chapters/030-nichtdiff/2-eckenbedingung.tex			\
	chapters/030-nichtdiff/3-splines.tex				\
	chapters/030-nichtdiff/fig/brechung.tex				\
	chapters/030-nichtdiff/fig/dbr.tex				\
	chapters/030-nichtdiff/fig/hermite.tex				\
	chapters/030-nichtdiff/fig/nichtdiff.tex			\
	chapters/030-nichtdiff/chapter.tex
