#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/010-fuvar/1-richtungsableitung.tex			\
	chapters/010-fuvar/2-kritisch.tex				\
	chapters/010-fuvar/3-nebenbedingungen.tex			\
	chapters/010-fuvar/4-hessesche.tex				\
	chapters/010-fuvar/5-quadratisch.tex				\
	chapters/010-fuvar/fig/tangentialebene.tex			\
	chapters/010-fuvar/fig/schwarz.tex				\
	chapters/010-fuvar/fig/karte.tex				\
	chapters/010-fuvar/fig/partrichtung.tex				\
	chapters/010-fuvar/fig/richtungsableitung.tex			\
	chapters/010-fuvar/fig/partabl.tex				\
	chapters/010-fuvar/fig/nebenbedingung.tex			\
	chapters/010-fuvar/chapter.tex
