#
# Makefile.inc -- Makefile dependencies for chapter 1
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/010-fuvar/1-richtungsableitung.tex			\
	chapters/010-fuvar/2-kritisch.tex				\
	chapters/010-fuvar/3-nebenbedingungen.tex			\
	chapters/010-fuvar/4-hessische.tex				\
	chapters/010-fuvar/5-quadratisch.tex				\
	chapters/010-fuvar/chapter.tex
