#
# Makefile -- build images
#
# (c) 2024 Prof Dr Andreas Müller
#
all:	emwelle.pdf pointcharge.pdf mfeld.pdf

emwelle.pdf:	emwelle.tex
	pdflatex emwelle.tex

pointcharge.pdf:	pointcharge.tex
	pdflatex pointcharge.tex

mfeld.pdf:	mfeld.tex
	pdflatex mfeld.tex

