#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-varalg =						\
	papers/varalg/packages.tex					\
	papers/varalg/main.tex					\
	papers/varalg/references.bib				\
	papers/varalg/teil0.tex					\
	papers/varalg/teil1.tex					\
	papers/varalg/teil2.tex					\
	papers/varalg/teil3.tex

