#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-kettenlinie =						\
	papers/kettenlinie/packages.tex					\
	papers/kettenlinie/main.tex					\
	papers/kettenlinie/references.bib				\
	papers/kettenlinie/teil0.tex					\
	papers/kettenlinie/teil1.tex					\
	papers/kettenlinie/teil2.tex					\
	papers/kettenlinie/teil3.tex

