#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-relativ =						\
	papers/relativ/packages.tex					\
	papers/relativ/main.tex					\
	papers/relativ/references.bib				\
	papers/relativ/teil0.tex					\
	papers/relativ/teil1.tex					\
	papers/relativ/teil2.tex					\
	papers/relativ/teil3.tex

