#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-relativ =							\
	papers/relativ/packages.tex					\
	papers/relativ/main.tex						\
	papers/relativ/references.bib				\
	papers/relativ/sections/relativistik.tex	\
	papers/relativ/sections/rel_mechanik.tex	\
	papers/relativ/sections/em_feld.tex
