#
# Makefile.inc -- Makefile dependencies for chapter 2
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/020-variation/1-problem.tex				\
	chapters/020-variation/2-fundamentallemma.tex			\
	chapters/020-variation/3-eulerlagrange.tex			\
	chapters/020-variation/4-hoehereableitungen.tex			\
	chapters/020-variation/5-mehrerefunktionen.tex			\
	chapters/020-variation/6-allgemein.tex				\
	chapters/020-variation/fig/brachistochronenproblem.tex		\
	chapters/020-variation/fig/f.tex				\
	chapters/020-variation/fig/g.tex				\
	chapters/020-variation/fig/variation.tex			\
	chapters/020-variation/fig/variation0.tex			\
	chapters/020-variation/fig/variation1.tex			\
	chapters/020-variation/uebungsaufgaben/201.tex			\
	chapters/020-variation/chapter.tex
