#
# Makefile.inc -- Makefile dependencies for chapter 2
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/020-variation/1-fundamentallemma.tex			\
	chapters/020-variation/2-eulerlagrange.tex			\
	chapters/020-variation/3-spliens.tex				\
	chapters/020-variation/4-hoehereableitungen.tex			\
	chapters/020-variation/5-mehrerefunktionen.tex			\
	chapters/020-fuvar/chapter.tex
