#
# Makefile.inc -- Makefile dependencies for chapter 2
#
# (c) 2023 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/020-variation/1-problem.tex				\
	chapters/020-variation/2-fundamentallemma.tex			\
	chapters/020-variation/3-eulerlagrange.tex			\
	chapters/020-variation/4-hoehereableitungen.tex			\
	chapters/020-variation/5-mehrerefunktionen.tex			\
	chapters/020-variation/6-allgemein.tex				\
	chapters/020-variation/chapter.tex
