#
# Makefile.inc
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter0 =								\
	../slides/0/xkcd.tex						\
	../slides/0/snell.tex						\
	../slides/0/fermat.tex						\
	../slides/0/problem.tex						\
	../slides/0/loesung.tex						\
	../slides/0/aufgabe.tex						\
	../slides/0/giant.tex						\
	../slides/0/info.tex						\
	../slides/0/was.tex						\
	../slides/0/frueher.tex						\
	../slides/0/themen.tex						\
	../slides/0/latextipps.tex					\
	../slides/0/nextsteps.tex					\
	../slides/0/inhalt.tex
