#
# Makefile.inc -- Makefile dependencies for chapter 8
#
# (c) 2024 Prof Dr Andreas Müller
#

CHAPTERFILES +=								\
	chapters/080-hamiltonjacobi/1-kanonisch.tex			\
	chapters/080-hamiltonjacobi/2-jacobi.tex			\
	chapters/080-hamiltonjacobi/3-oc.tex				\
	chapters/080-hamiltonjacobi/fig/oc.tex				\
	chapters/080-hamiltonjacobi/fig/eindim.tex			\
	chapters/080-hamiltonjacobi/chapter.tex
