#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-leo =						\
	papers/leo/packages.tex					\
	papers/leo/main.tex					\
	papers/leo/references.bib				\
	papers/leo/teil0.tex					\
	papers/leo/teil1.tex					\
	papers/leo/teil2.tex					\
	papers/leo/teil3.tex

