#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-leo =						\
	papers/leo/packages.tex					\
	papers/leo/main.tex					\
	papers/leo/references.bib				\
	papers/leo/0_einleitung.tex				\
	papers/leo/1_physik.tex					\
	papers/leo/2_aufstiegsgleichung.tex			\
	papers/leo/3_mathe.tex					\
	papers/leo/4_vereinfachungen.tex			\
	papers/leo/5_beispiel.tex

