#
# Makefile -- build images
#
# (c) 2023 Prof Dr Andreas Müller
#
all:	dido.pdf heaviside.pdf cos2.pdf yk.pdf seilbahn.pdf

dido.pdf:	dido.tex
	pdflatex dido.tex

heaviside.pdf:	heaviside.tex
	pdflatex heaviside.tex

cos2.pdf:	cos2.tex
	pdflatex cos2.tex

yk.pdf:	yk.tex
	pdflatex yk.tex

seilbahn.pdf:	seilbahn.tex
	pdflatex seilbahn.tex
