#
# Makefile.inc
#
# (c) 2023 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
chapter1 =								\
	../slides/1/partabl.tex						\
	../slides/1/richtungsableitung.tex				\
	../slides/1/schwarz.tex
