#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-antennen =						\
	papers/antennen/packages.tex					\
	papers/antennen/main.tex					\
	papers/antennen/references.bib				\
	papers/antennen/teil0.tex					\
	papers/antennen/teil1.tex					\
	papers/antennen/teil2.tex					\
	papers/antennen/teil3.tex

