#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-antennen =							\
	papers/antennen/packages.tex					\
	papers/antennen/main.tex					\
	papers/antennen/references.bib					\
	papers/antennen/problemstellung.tex				\
	papers/antennen/antennenAllgemein.tex				\
	papers/antennen/ritzAufProblem.tex				\
	papers/antennen/unserRitz.tex

