include papers/doppelpendel/Makefile.inc
include papers/kettenlinie/Makefile.inc
include papers/balken/Makefile.inc
include papers/relativ/Makefile.inc
include papers/maxwell/Makefile.inc
include papers/geodaeten/Makefile.inc
include papers/minimalflaechen/Makefile.inc
include papers/leo/Makefile.inc
include papers/circuit/Makefile.inc
include papers/antennen/Makefile.inc
include papers/fem/Makefile.inc
include papers/schwimmen/Makefile.inc
include papers/planet/Makefile.inc
include papers/varalg/Makefile.inc
include papers/cahnhilliard/Makefile.inc
include papers/luke/Makefile.inc
include papers/widerstand/Makefile.inc

TEXFILES = \
	$(dependencies-doppelpendel) \
	$(dependencies-kettenlinie) \
	$(dependencies-balken) \
	$(dependencies-relativ) \
	$(dependencies-maxwell) \
	$(dependencies-geodaeten) \
	$(dependencies-minimalflaechen) \
	$(dependencies-leo) \
	$(dependencies-circuit) \
	$(dependencies-antennen) \
	$(dependencies-fem) \
	$(dependencies-schwimmen) \
	$(dependencies-planet) \
	$(dependencies-varalg) \
	$(dependencies-cahnhilliard) \
	$(dependencies-luke) \
	$(dependencies-widerstand) \

