#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-fem =							\
	papers/fem/packages.tex					\
	papers/fem/main.tex						\
	papers/fem/references.bib				\
	papers/fem/0_einleitung.tex				\
	papers/fem/1_prinzip_1d.tex				\
	papers/fem/2_erweiterung_nD.tex			\
	papers/fem/3_rechenbeispiel.tex			\
	papers/fem/4_matlab.tex 				\
	papers/fem/5_anwendungen.tex			\
	papers/fem/custom_commands.tex

