#
# Makefile.inc -- dependencies for this article
#
# (c) 2021 Prof Dr Andreas Müller, OST Ostschweizer Fachhochschule
#
dependencies-fem =						\
	papers/fem/packages.tex					\
	papers/fem/main.tex					\
	papers/fem/references.bib				\
	papers/fem/teil0.tex					\
	papers/fem/teil1.tex					\
	papers/fem/teil2.tex					\
	papers/fem/teil3.tex

